<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>cb701d81-f460-4835-9cbb-cded3986a7de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer-link-presskit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='footer-link-presskit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c07509c0-6421-4ebb-acb1-239446f19544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>fa1a67c9-bcff-4b76-a139-e859d10c1e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer-link-presskit</value>
      <webElementGuid>e08cd09b-b598-4641-ac25-464bccf22bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://drive.google.com/drive/folders/1-NWcADScmGXPmax3LO2z0k74RfgjWpZx</value>
      <webElementGuid>24bad459-fbd0-4f13-bb75-d4d96a0daaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-msst9f</value>
      <webElementGuid>5a062ba8-73b0-42fe-a278-b2f7cfc9ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>프레스 키트</value>
      <webElementGuid>4689c0d2-195b-4eda-abf2-881ef2682020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-link-presskit&quot;)</value>
      <webElementGuid>92c9d9c8-2340-437c-85b4-c75753dc8407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='footer-link-presskit']</value>
      <webElementGuid>309a610a-4e2e-463a-befd-85061389f48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/footer/div/a</value>
      <webElementGuid>989743e4-a835-4d1e-82e0-402cee58c622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'프레스 키트')]</value>
      <webElementGuid>dac51963-04e0-4a5c-bcbf-c1ea76778140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOLLOW US!'])[1]/following::a[5]</value>
      <webElementGuid>97b6aafb-5e37-41ae-adc0-057ea9ef962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='공식 커뮤니티'])[1]/following::a[5]</value>
      <webElementGuid>8e1da6e3-c133-416a-a606-5da102d9de00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인정보처리방침'])[1]/preceding::a[1]</value>
      <webElementGuid>2203d86f-f321-4fae-b517-75ff5beab133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이용약관'])[1]/preceding::a[2]</value>
      <webElementGuid>603836e3-4bd3-46d9-9d4a-c83d489f4401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='프레스 키트']/parent::*</value>
      <webElementGuid>0c2910e9-a9bf-4500-bb9c-d49eb0d1641b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://drive.google.com/drive/folders/1-NWcADScmGXPmax3LO2z0k74RfgjWpZx')]</value>
      <webElementGuid>76b9f30d-bd4c-40ea-9ca5-cb9341bd30e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/a</value>
      <webElementGuid>fbdf15fc-24f4-4b59-8545-47315de1711d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'footer-link-presskit' and @href = 'https://drive.google.com/drive/folders/1-NWcADScmGXPmax3LO2z0k74RfgjWpZx' and (text() = '프레스 키트' or . = '프레스 키트')]</value>
      <webElementGuid>4c02c5b0-13ea-402b-9ca5-464d2e29888f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
