<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1 -</name>
   <tag></tag>
   <elementGuidId>d1af74f9-2dba-40a4-a459-de39e6fcbc26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_49']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f37e13d7-c72d-4509-b213-0666f5dc1677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ</value>
      <webElementGuid>ebfcdd97-5994-4b9d-a9c1-2b8562c86862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 1 - 지구로 돌아갑시다</value>
      <webElementGuid>4decf039-5133-4ac7-bbac-d2c7a8f1e6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_49&quot;)/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>78d81eea-08ce-4fec-b31d-4aa9c99a7425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d44399a5-27bd-4767-84ee-a8022806d6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ</value>
      <webElementGuid>d9155f82-ba3a-4194-a93c-a2ef32334908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 1 - 지구로 돌아갑시다</value>
      <webElementGuid>eaff54e7-3f3a-43ac-9495-47c0721cb248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_49&quot;)/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>a219bc75-0521-4be2-8964-fd8f63300f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9aa6db84-c043-42d3-b64c-c486c2bf1ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ</value>
      <webElementGuid>9ea46e6a-2dee-4c54-b49c-de3a1d041384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 1 - 지구로 돌아갑시다</value>
      <webElementGuid>4f32d7ce-f0ee-4864-ae0a-8660ee42ae14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_49&quot;)/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>95bd2023-89e1-432d-b198-6fb2dc754e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>408f0c81-d234-4fd7-b5eb-7ad997f3986d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ</value>
      <webElementGuid>ab19e48e-68ba-4f91-8928-f317b13ff0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 1 - 지구로 돌아갑시다</value>
      <webElementGuid>a940f31d-0a53-4948-847c-98fd344d77d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_49&quot;)/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>f28e327f-9935-4cbe-b668-22e94680b817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_49']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      <webElementGuid>af625e8f-633e-4efb-991f-9d5c7911bfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'챕터 1 - 지구로 돌아갑시다')]</value>
      <webElementGuid>0cc69398-c05b-44fe-b5a5-c425a116186a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 목록'])[2]/following::a[2]</value>
      <webElementGuid>4799368a-047f-4d0d-a107-a06efd5557f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in browser'])[1]/following::a[5]</value>
      <webElementGuid>df0ab104-8435-4caf-8726-6a935794c066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 2 - 일반참가자 전용안내서'])[1]/preceding::a[4]</value>
      <webElementGuid>20859e71-c7df-42be-94e8-054391cb9459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 3 - 브릭 아카데미'])[1]/preceding::a[9]</value>
      <webElementGuid>2de1aefd-a7df-448a-a02a-754d600e1d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='챕터 1 - 지구로 돌아갑시다']/parent::*</value>
      <webElementGuid>e1f3140f-46f1-4ce3-abec-b7bd2ab69f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ')]</value>
      <webElementGuid>3c8f189b-71a5-450b-ad24-8c2eb2f9f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/a</value>
      <webElementGuid>7ee62337-ed8c-4a37-b5a4-ddadc708e7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/fpJ3-VpfSTEk7MHXa9BzIe24XwwC-anaUy0YSRDG3hP3_pHSnzAWBl6c3feGCK_mutyB3OVNkS_sbULmnXM32ivOfCqqrXTi6fndJ490jb1CF3mkWQ' and (text() = '챕터 1 - 지구로 돌아갑시다' or . = '챕터 1 - 지구로 돌아갑시다')]</value>
      <webElementGuid>69cd68cd-d0a0-4fd9-b938-1420b82fc2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
