<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2 -</name>
   <tag></tag>
   <elementGuidId>16b1c1d7-8d7e-49f0-a406-8b068926c2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cec838a-93cf-43db-a1db-789f0c002094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/ldx8NxbqHbHt3e2Pl1GrGV7DSgdDlkYjE3pUeeraez4soxdzbWfSbvBpC0527fiMcfguzIJ7c8qXr2KzpOiSMRvkz2qi3_ey9hFhPPuxyCkBbpWSyg</value>
      <webElementGuid>ea1b0e79-9b38-425b-b0d3-6040638ded1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 2 - 일반참가자 전용안내서</value>
      <webElementGuid>45e11231-a45c-45b4-b53c-5c93414b75f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[6]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>211bc4a1-fbfa-41a9-b922-9570bdd1bf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a997e762-89b5-4646-a5ff-20f58a0071f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/ldx8NxbqHbHt3e2Pl1GrGV7DSgdDlkYjE3pUeeraez4soxdzbWfSbvBpC0527fiMcfguzIJ7c8qXr2KzpOiSMRvkz2qi3_ey9hFhPPuxyCkBbpWSyg</value>
      <webElementGuid>a4ffa4cd-6558-4a65-9134-1120c7eccce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 2 - 일반참가자 전용안내서</value>
      <webElementGuid>a8862e8a-f6b3-43bd-aa22-fbafdfb46213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[6]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>856c624b-514e-4bd9-b8e8-e9ed45f9b97a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      <webElementGuid>a693901f-419d-4a6e-9125-86e6a3e7161b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'챕터 2 - 일반참가자 전용안내서')]</value>
      <webElementGuid>f6e6fa9c-2018-4f51-9e5b-20696151b36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 1 - 지구로 돌아갑시다'])[1]/following::a[4]</value>
      <webElementGuid>c1849a88-6b16-4726-9d0f-ef701f750f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 목록'])[2]/following::a[6]</value>
      <webElementGuid>913b02da-ae37-4150-975b-2013d05a26ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 3 - 브릭 아카데미'])[1]/preceding::a[5]</value>
      <webElementGuid>4a298db3-fc42-4da0-9795-2e12a2610041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 4 - 화성에서 지구로'])[1]/preceding::a[10]</value>
      <webElementGuid>9934787b-c1f1-41b5-b59c-2a59f23c99a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='챕터 2 - 일반참가자 전용안내서']/parent::*</value>
      <webElementGuid>606fd58d-5aa7-4a91-8d89-49e797ea6e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/ldx8NxbqHbHt3e2Pl1GrGV7DSgdDlkYjE3pUeeraez4soxdzbWfSbvBpC0527fiMcfguzIJ7c8qXr2KzpOiSMRvkz2qi3_ey9hFhPPuxyCkBbpWSyg')]</value>
      <webElementGuid>08e5987e-cc14-4ab1-8837-2bfce9fcdaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      <webElementGuid>57203f1b-c6d1-420a-b0a3-e4ffbd95c6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/ldx8NxbqHbHt3e2Pl1GrGV7DSgdDlkYjE3pUeeraez4soxdzbWfSbvBpC0527fiMcfguzIJ7c8qXr2KzpOiSMRvkz2qi3_ey9hFhPPuxyCkBbpWSyg' and (text() = '챕터 2 - 일반참가자 전용안내서' or . = '챕터 2 - 일반참가자 전용안내서')]</value>
      <webElementGuid>b997f8e8-a98f-44db-a9ac-698489181d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
