<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3 -</name>
   <tag></tag>
   <elementGuidId>982f2e6d-5383-4a5f-a905-b810d45341ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3026943-e5d9-4e35-a1c9-c1ca92a8c103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/tb0GBWm1boGOz4i4q3fODKi-V3FoJ-DpCf2wOrRFLmyac5VEFFuiLqYWjaxjJmQsu4D9Z7MbJWzEUgVb-BBWHwvsEnPpxnlDJWn5p1GC8fDUdwdAqg</value>
      <webElementGuid>14c9aa95-d5bf-4054-acdf-886a8f81a162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 3 - 브릭 아카데미</value>
      <webElementGuid>aa3c99c0-332a-467f-9312-a70289f8bbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[8]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>79c0f028-084e-40bb-9559-8bc6f353830d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>679a920c-d204-4cfd-9fe1-f2846b67a876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/tb0GBWm1boGOz4i4q3fODKi-V3FoJ-DpCf2wOrRFLmyac5VEFFuiLqYWjaxjJmQsu4D9Z7MbJWzEUgVb-BBWHwvsEnPpxnlDJWn5p1GC8fDUdwdAqg</value>
      <webElementGuid>72014551-aad1-4249-8e81-00d4157484a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 3 - 브릭 아카데미</value>
      <webElementGuid>77315928-3414-41d4-ad44-036a211635c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[8]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>67caca52-bcd8-4397-9777-e459d12f196c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a)[2]</value>
      <webElementGuid>31378893-298c-4502-9804-f75fa69a9c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'챕터 3 - 브릭 아카데미')]</value>
      <webElementGuid>11c75ae3-f86d-4e93-ba8d-793523198287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 2 - 일반참가자 전용안내서'])[1]/following::a[5]</value>
      <webElementGuid>3f0d1e84-568d-46b2-8b0b-de4e781f0c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 1 - 지구로 돌아갑시다'])[1]/following::a[9]</value>
      <webElementGuid>25188b26-cff6-490b-a34a-d162feb1bcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 4 - 화성에서 지구로'])[1]/preceding::a[5]</value>
      <webElementGuid>13df9dd7-9603-44df-906f-dcde2377b0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 5 - 옛 지구를 찾아서'])[1]/preceding::a[10]</value>
      <webElementGuid>c4509ea3-f7d6-49d5-bd38-55e647e87632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='챕터 3 - 브릭 아카데미']/parent::*</value>
      <webElementGuid>ff01c378-5f74-4542-a66b-32e7b7de708c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/tb0GBWm1boGOz4i4q3fODKi-V3FoJ-DpCf2wOrRFLmyac5VEFFuiLqYWjaxjJmQsu4D9Z7MbJWzEUgVb-BBWHwvsEnPpxnlDJWn5p1GC8fDUdwdAqg')]</value>
      <webElementGuid>7c3fd5ae-b993-41a1-b07f-ca3018635d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      <webElementGuid>e32dfb28-f22f-40ea-a702-896451b272a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/tb0GBWm1boGOz4i4q3fODKi-V3FoJ-DpCf2wOrRFLmyac5VEFFuiLqYWjaxjJmQsu4D9Z7MbJWzEUgVb-BBWHwvsEnPpxnlDJWn5p1GC8fDUdwdAqg' and (text() = '챕터 3 - 브릭 아카데미' or . = '챕터 3 - 브릭 아카데미')]</value>
      <webElementGuid>e5c7d06e-e58c-4426-8895-91d04a331a09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
