<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4 -</name>
   <tag></tag>
   <elementGuidId>6d8d5cef-8389-49d1-bee1-ebb0fa4aac37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1834e86c-f092-4379-8968-b19705dcc679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/06DXATVuqh0857wZyQggWq7g9d6ipB7yDyaV_BC_N_Xu8KwNZ0aJL-b_KbFGdj4KYyPdXZ5LYF2ffNXkDWreO304ZqD9ROwZOapdy8u6_tDsobAfAg</value>
      <webElementGuid>ea2502db-abb4-412a-8aea-b41eb0130009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 4 - 화성에서 지구로</value>
      <webElementGuid>dc4b183a-4e8b-4e37-af9f-490cd46875c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[10]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>60d9441d-5308-488d-b420-d4551818eacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c77a53b-ccb3-48d2-974d-9fb0c758b86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/06DXATVuqh0857wZyQggWq7g9d6ipB7yDyaV_BC_N_Xu8KwNZ0aJL-b_KbFGdj4KYyPdXZ5LYF2ffNXkDWreO304ZqD9ROwZOapdy8u6_tDsobAfAg</value>
      <webElementGuid>b7bae1c1-89b8-4998-881f-939c9da71c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>챕터 4 - 화성에서 지구로</value>
      <webElementGuid>69eb306d-89b2-4752-8e6d-1e672948a1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[10]/td[1]/div[1]/table[@id=&quot;Layout_50&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[2]/td[1]/span[1]/span[1]/b[1]/a[1]</value>
      <webElementGuid>e53d5e3c-dec8-484f-9cce-e7a7ddbd83aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='Layout_50']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a)[3]</value>
      <webElementGuid>20d8cd98-a14f-4539-8a5e-d210188062a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'챕터 4 - 화성에서 지구로')]</value>
      <webElementGuid>17656676-77f5-449c-bb22-5db718f198a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 3 - 브릭 아카데미'])[1]/following::a[5]</value>
      <webElementGuid>14bc2c6e-abce-4e74-bdef-1c06a8110498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 2 - 일반참가자 전용안내서'])[1]/following::a[10]</value>
      <webElementGuid>2113cd2e-bb80-4259-b577-f8721bb34955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='챕터 5 - 옛 지구를 찾아서'])[1]/preceding::a[5]</value>
      <webElementGuid>c4166719-7803-4e5c-abfd-71c522f29255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='챕터 4 - 화성에서 지구로']/parent::*</value>
      <webElementGuid>09f374f3-84b9-40ac-af01-a519738526e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/06DXATVuqh0857wZyQggWq7g9d6ipB7yDyaV_BC_N_Xu8KwNZ0aJL-b_KbFGdj4KYyPdXZ5LYF2ffNXkDWreO304ZqD9ROwZOapdy8u6_tDsobAfAg')]</value>
      <webElementGuid>4115d962-9cbc-4b2c-a20e-f8bc27059c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/th/table/tbody/tr[2]/td/span/span/b/a</value>
      <webElementGuid>acde0b54-c3a4-4f50-9dbd-690cc0577128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/06DXATVuqh0857wZyQggWq7g9d6ipB7yDyaV_BC_N_Xu8KwNZ0aJL-b_KbFGdj4KYyPdXZ5LYF2ffNXkDWreO304ZqD9ROwZOapdy8u6_tDsobAfAg' and (text() = '챕터 4 - 화성에서 지구로' or . = '챕터 4 - 화성에서 지구로')]</value>
      <webElementGuid>ee9414f8-7a80-49a8-a918-0bbd1592f7b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
