<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1_2</name>
   <tag></tag>
   <elementGuidId>08b13c6c-081b-4887-82e8-1809093e4046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer-link-terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='footer-link-terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e493a5c9-d374-44d3-b59b-ee59e72c0ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a0b08465-b0d2-4275-8b7b-36ac4cd82ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer-link-terms</value>
      <webElementGuid>bf871b3c-939b-4b6b-9665-383c58a02be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://policy.devsisters.com/ko/terms-of-service</value>
      <webElementGuid>873852c6-2bef-42d1-88a2-5fa6cdc18dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-msst9f</value>
      <webElementGuid>4b21932a-9b6b-4946-a55c-38ec9e7de466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>이용약관</value>
      <webElementGuid>8afb88da-267d-4d84-af93-fff0700b1b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-link-terms&quot;)</value>
      <webElementGuid>66eb1010-d83c-47f5-8db0-240190536209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='footer-link-terms']</value>
      <webElementGuid>df8118a6-36a0-4f0a-b3a4-9c3ddbfbae16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/footer/div/a[3]</value>
      <webElementGuid>49ab2a24-a566-4780-b6fd-5ee773c7f870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'이용약관')]</value>
      <webElementGuid>fbe29ae4-9fa3-48f4-a850-a38ff2cf44eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인정보처리방침'])[1]/following::a[1]</value>
      <webElementGuid>9b9af2c2-2655-4e36-9988-67627a1244c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='프레스 키트'])[1]/following::a[2]</value>
      <webElementGuid>4b1677ce-da20-4503-b436-52ee7e683f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'footer-link-terms', '&quot;', ')')])[1]/preceding::a[2]</value>
      <webElementGuid>1fd580f2-8869-4f3d-8568-388755ca3ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='이용약관']/parent::*</value>
      <webElementGuid>7f162999-203b-4ee2-aee6-56267b1174ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://policy.devsisters.com/ko/terms-of-service')]</value>
      <webElementGuid>17f5e589-9d3f-4b11-a05e-f85fa03e2217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/a[3]</value>
      <webElementGuid>1e7dfded-8721-43d3-9b3a-e951fa3b7537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'footer-link-terms' and @href = 'https://policy.devsisters.com/ko/terms-of-service' and (text() = '이용약관' or . = '이용약관')]</value>
      <webElementGuid>5e5a2e12-dc1b-49b8-921b-24e804c290c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
