<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>80532a98-b13d-4a01-8f10-7001d19f931f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer-link-privacy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='footer-link-privacy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61e70ea9-2c2f-436e-aead-9ae4af43e313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c74ab1bf-c270-4698-a240-87d2bbfebe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer-link-privacy</value>
      <webElementGuid>5b9ac299-7fe7-4ceb-85b1-4b545425fd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://policy.devsisters.com/ko/privacy</value>
      <webElementGuid>43c0c35b-6d47-476c-a224-92bc6f5387f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-e78odb</value>
      <webElementGuid>ae70697f-2b70-4f85-bd47-cd26671a52eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>개인정보처리방침</value>
      <webElementGuid>ab33aea5-d431-48b8-8307-c5b436105bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer-link-privacy&quot;)</value>
      <webElementGuid>1e8198de-39be-495b-ba51-a2780e2877b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='footer-link-privacy']</value>
      <webElementGuid>34b01348-bd27-455e-a5da-f8994adf3d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/footer/div/a[2]</value>
      <webElementGuid>2f06b3e9-5998-4c47-9adf-33ce9734abf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'개인정보처리방침')]</value>
      <webElementGuid>0764d0b9-c8fb-40d7-8d9a-8cd8597de793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='프레스 키트'])[1]/following::a[1]</value>
      <webElementGuid>49451d37-0764-48ae-80f5-023b6d51c060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FOLLOW US!'])[1]/following::a[6]</value>
      <webElementGuid>c9f42c54-c026-4918-9eb2-77a99b171c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이용약관'])[1]/preceding::a[1]</value>
      <webElementGuid>8804451e-f56e-4633-90d5-bce1a146bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'footer-link-privacy', '&quot;', ')')])[1]/preceding::a[3]</value>
      <webElementGuid>973bf548-c702-4842-a9e0-7d096205b96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='개인정보처리방침']/parent::*</value>
      <webElementGuid>7e2d3936-878b-4d95-a4a6-bde2defb60eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://policy.devsisters.com/ko/privacy')]</value>
      <webElementGuid>4e84bbbd-a083-4281-944c-ecfd69efbe6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/a[2]</value>
      <webElementGuid>8dccb7f6-005c-44d4-a67e-db56ae59bb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'footer-link-privacy' and @href = 'https://policy.devsisters.com/ko/privacy' and (text() = '개인정보처리방침' or . = '개인정보처리방침')]</value>
      <webElementGuid>18055f91-8dbe-4be2-9466-008ac3755d4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
