<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>663afb40-c990-42c4-92fc-ccd4907fec0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-about</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='global-navigation-about']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e25b4cb6-f43a-4ca6-8efc-3e66cb4dd125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-about</value>
      <webElementGuid>bb6fbdb9-f7fc-4f4e-aaf0-9edb7d80f1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>1d90c9ca-16a8-4546-8dee-53b67231acc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>게임 소개</value>
      <webElementGuid>3df96070-5775-4e2d-960a-43f959c0c182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-about&quot;)</value>
      <webElementGuid>cd335c80-a663-4b1f-8d2c-1f3fe245b2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2149b719-e60a-437c-9a5b-35595a5e535f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-about</value>
      <webElementGuid>97183862-4745-4fb5-a914-50b03c84f98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>bb4940fb-cb33-43af-bd4d-87db643bb91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>게임 소개</value>
      <webElementGuid>7b264c75-6139-4dbd-b4c4-8463c03f469f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-about&quot;)</value>
      <webElementGuid>8a6f1d38-3626-40ca-bfc2-271bead04757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07d15aef-f80f-40a6-9de0-c481b2a21474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-about</value>
      <webElementGuid>5de924f2-74a2-4dda-92e9-aa68d4dd3ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>49e18312-b0d9-48f8-9041-cab91c53e170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>게임 소개</value>
      <webElementGuid>14b7b07b-35ba-48ef-93f6-509b44b0ee1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-about&quot;)</value>
      <webElementGuid>24e00d3a-0b59-409f-b80d-b6e00a7c9967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b119673-1168-43fb-9622-ff6a685d6714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-about</value>
      <webElementGuid>df9881e3-cf25-420a-a10c-816296f6c990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>d5608573-ef75-4e3b-a02b-c0bd06b26286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>게임 소개</value>
      <webElementGuid>5a7cadb6-3f28-4090-a5fd-a4a1bd34847c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-about&quot;)</value>
      <webElementGuid>ddb804b6-0ed9-454f-80ab-d78309e715f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='global-navigation-about']</value>
      <webElementGuid>a432cdce-6e25-4db9-aa61-ec9b06428fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/nav/div/ul/li[2]/button</value>
      <webElementGuid>3cb566b2-cf85-470e-a618-b0df4fd1e319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='홈'])[1]/following::button[1]</value>
      <webElementGuid>1ec91567-a5d5-4f21-97d5-95f23f0b9ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='쿠키런: 퍼즐월드'])[2]/following::button[3]</value>
      <webElementGuid>1ce4bb86-f606-4f1e-9ea8-51539fa7691e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커뮤니티'])[1]/preceding::button[1]</value>
      <webElementGuid>7c6d045f-2830-44e4-a25d-52d63bd1da56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/preceding::button[2]</value>
      <webElementGuid>faa33dc2-92fa-4345-a157-5ce55cfeae28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='게임 소개']/parent::*</value>
      <webElementGuid>28662687-87a4-4a0a-b7e2-de2796dae766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>64e62acf-6998-415d-acbb-9e505989aa1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'global-navigation-about' and (text() = '게임 소개' or . = '게임 소개')]</value>
      <webElementGuid>a7aff8ec-6876-4b57-8df8-52ab35a007b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
