<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>423a076c-f8fc-4d4e-9e62-a27697a2de3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='global-navigation-home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52226da5-f835-437d-946b-53018b257bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-home</value>
      <webElementGuid>9ab75ccb-78da-47f4-9204-5a3ab7fa52f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>e7fe3540-8203-4a45-a5f9-7054d0b00863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>홈</value>
      <webElementGuid>66d313e8-95c5-45b3-8e1d-0e10961df6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-home&quot;)</value>
      <webElementGuid>54663a4e-9582-45f2-a00b-557a1d7ba934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='global-navigation-home']</value>
      <webElementGuid>74969e11-c84e-4209-a71c-9ec9fcba4e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/nav/div/ul/li/button</value>
      <webElementGuid>38128bf9-805f-4aad-89ee-f5aecb3238a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='쿠키런: 퍼즐월드'])[2]/following::button[2]</value>
      <webElementGuid>fcdc0cbd-93c5-42cb-b5d5-edc4c1290725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='쿠키런: 킹덤'])[2]/following::button[2]</value>
      <webElementGuid>0b2c88e3-6f42-49b2-84fb-70602188cae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임 소개'])[1]/preceding::button[1]</value>
      <webElementGuid>f150dfe7-bf91-4a54-a3c8-a2257b51a056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커뮤니티'])[1]/preceding::button[2]</value>
      <webElementGuid>4ff7f3a4-65f3-444f-abe9-69d56694fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='홈']/parent::*</value>
      <webElementGuid>cd637ac3-87a6-4ebe-9182-b451cc32aeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>87689f7d-de72-424c-a347-8325bb8da23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'global-navigation-home' and (text() = '홈' or . = '홈')]</value>
      <webElementGuid>7080180d-9193-4374-a906-2c422d4f7384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
