<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>2891df93-03e4-46db-81a1-cc20f8d73806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-community</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='global-navigation-community']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81479627-f95b-4311-ba0f-8efe006d5c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-community</value>
      <webElementGuid>2c273815-4b64-4fcc-b155-ee63a0ec98e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>a6107cd0-b05f-4305-8298-54c948824ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>커뮤니티</value>
      <webElementGuid>6d3b7eb7-cad8-453a-a846-0f008a19e4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-community&quot;)</value>
      <webElementGuid>baee03fe-36b1-4368-93d0-fb6f184a177a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='global-navigation-community']</value>
      <webElementGuid>18c7dd1e-6498-4098-8f53-edbb2948476a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/nav/div/ul/li[3]/button</value>
      <webElementGuid>1fa2b8cd-58f3-4364-8337-d181fb8b8f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임 소개'])[1]/following::button[1]</value>
      <webElementGuid>2aff4799-1345-4d33-a884-d8e97b91c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='홈'])[1]/following::button[2]</value>
      <webElementGuid>fe830681-c96a-480c-a217-64842cd44ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/preceding::button[1]</value>
      <webElementGuid>577edc4b-4c19-4299-9dc2-9939c36db962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/preceding::button[4]</value>
      <webElementGuid>10a55707-a68b-4b1b-ad05-61950a5e7016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='커뮤니티']/parent::*</value>
      <webElementGuid>8c74af24-bd20-4138-8d8c-290b1f3a2472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>6531c3cb-0dda-487e-9858-9ac540471159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'global-navigation-community' and (text() = '커뮤니티' or . = '커뮤니티')]</value>
      <webElementGuid>71a6ba30-1398-4198-a912-52565dcaf72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
