<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>2de725a8-2630-4097-9d82-89fdc5703c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-guidebook</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='global-navigation-guidebook']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbd53a4a-b907-40a6-bcd8-52e1f0896a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-navigation-guidebook</value>
      <webElementGuid>0b33f7de-e4b2-4a02-83e0-1424b60e77f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1253f98a-3b82-47bd-b949-52c5bc2241f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kdzvu3</value>
      <webElementGuid>520a91a8-9b71-4eb8-be11-0c0e71f112cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>가이드북</value>
      <webElementGuid>70204dba-5cac-4852-b486-b20bf95b8b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-guidebook&quot;)</value>
      <webElementGuid>82db5434-b121-4846-9715-9af98f5af5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='global-navigation-guidebook']</value>
      <webElementGuid>8608bc22-808e-476c-a4d7-3dcf77ec68ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top']/nav/div/ul/li[4]/a/button</value>
      <webElementGuid>f5ef0d1b-daa8-4bb2-bc91-3626a9416e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커뮤니티'])[1]/following::button[1]</value>
      <webElementGuid>4c5640e8-da52-481d-a174-2c54e947e03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임 소개'])[1]/following::button[2]</value>
      <webElementGuid>1d8e7bf1-c8e0-4ba1-b1cb-f6ebc4b369cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/preceding::button[3]</value>
      <webElementGuid>349ac31a-d93f-44af-9216-f585fbca7552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='자세히 보기'])[1]/preceding::button[4]</value>
      <webElementGuid>000f8a35-978b-4ad8-aaac-01cd64a8c9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='가이드북']/parent::*</value>
      <webElementGuid>4679e706-52a5-4e30-b2b6-1dc079136268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>0bd485d9-d4b9-43eb-b4be-f220eae28afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'global-navigation-guidebook' and @type = 'button' and (text() = '가이드북' or . = '가이드북')]</value>
      <webElementGuid>a36ace3a-71d7-4710-bea8-fe04774bb5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
