<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>7097ad51-ff75-4064-a9c8-d35b9bbd5855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-youtube > svg.css-uwwqev > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>c10e2346-7f15-4e70-bc45-8f0ed61a4039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7860b9da-f0d7-434c-9053-8ff33818f756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>33dd5001-6cd5-41eb-92dd-662db7b9e4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>64010bc8-cd4d-4dd7-8c80-6af875f4c9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#C7252D</value>
      <webElementGuid>a68a25f9-adbd-494c-9ba7-80d6c6ea2104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-youtube&quot;)/svg[@class=&quot;css-uwwqev&quot;]/circle[1]</value>
      <webElementGuid>cf7a1ea4-ff9e-4797-9480-b7e94daf2a7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
