<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__css-1mby5p4</name>
   <tag></tag>
   <elementGuidId>d1281cdd-8979-4181-aff4-a2fd39cb3549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-1mby5p4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e67a294-9aab-4a5e-9ea6-566c17c6be49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>이메일을 입력해주세요</value>
      <webElementGuid>22160f30-ed2b-4d0f-bb7e-67bf9298fb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1mby5p4</value>
      <webElementGuid>91e75f9b-d69f-4c12-8965-dcfd33574047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;gbi-1208751019-kMRAbbvUQYqJRSjgFumbPF&quot;]/div[@class=&quot;css-ae0qq0&quot;]/form[1]/div[@class=&quot;css-29nxvx&quot;]/input[@class=&quot;css-1mby5p4&quot;]</value>
      <webElementGuid>27a9519d-63a8-4e08-bba1-b41ba7b3ac3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>bf97aa84-9f2b-4d7b-8e6c-027725c91d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/form/div/input</value>
      <webElementGuid>394d9086-3ed3-4470-a944-755fc217e578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>35072ba3-ebc3-44b3-9591-f3d82716e856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '이메일을 입력해주세요']</value>
      <webElementGuid>d3812806-ccb5-460c-a1a4-8f1bbf0db6c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
