<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_327</name>
   <tag></tag>
   <elementGuidId>dc4edf54-bca4-4087-afcb-feaf99b11a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-tp909m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/footer/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>60248483-66c0-4175-ae3f-c2ac7893b14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-tp909m</value>
      <webElementGuid>6bc03b53-6918-4abb-a3b0-547556d4ce37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>서울특별시 강남구 도산대로 327</value>
      <webElementGuid>aac05e9c-8c76-4d4e-8e0f-cd67a4eeb359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;css-pdjuhq&quot;]/footer[@class=&quot;css-1ulsyan&quot;]/div[@class=&quot;css-15g68ba&quot;]/p[@class=&quot;css-tp909m&quot;]</value>
      <webElementGuid>a3446fd0-2e93-4227-9375-3dffefc10001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/footer/div[2]/p</value>
      <webElementGuid>75adbcf1-ac61-4359-b817-bc4b9fa50bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이용약관'])[1]/following::p[1]</value>
      <webElementGuid>991900bc-c67f-4fa6-bcc4-0526d0438ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='개인정보처리방침'])[1]/following::p[1]</value>
      <webElementGuid>1b86690d-891c-43f5-8209-d9a5356f891c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='서울특별시 강남구 도산대로 327']/parent::*</value>
      <webElementGuid>767b6fd8-908c-45ee-9910-3d41cc3efb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>652fa40c-16b2-4a59-9f82-142dbf775ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '서울특별시 강남구 도산대로 327' or . = '서울특별시 강남구 도산대로 327')]</value>
      <webElementGuid>de1e5a73-0ea0-4098-9ee3-b6e795f77739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
