<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__css-12pj4y1</name>
   <tag></tag>
   <elementGuidId>99ebceb3-310c-482b-ad2a-5113591fd969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.css-12pj4y1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home']/div/div/form/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8f744ce-ea5f-429d-b982-fa877c302128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-12pj4y1</value>
      <webElementGuid>700b9402-7398-4472-a4a6-19f7835aca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;gbi-1208751019-kMRAbbvUQYqJRSjgFumbPF&quot;]/div[@class=&quot;css-ae0qq0&quot;]/form[1]/div[@class=&quot;css-1f3t5ys&quot;]/label[@class=&quot;css-139h8vn&quot;]/span[@class=&quot;css-12pj4y1&quot;]</value>
      <webElementGuid>fd916cf0-b72d-4658-a766-628e8a12d58d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home']/div/div/form/div[2]/label/span</value>
      <webElementGuid>4cb794e9-ddb4-4120-9d8d-368d8588ad58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/following::span[1]</value>
      <webElementGuid>ea3d0570-6a88-49d4-9168-7ff56fcc6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/following::span[5]</value>
      <webElementGuid>ba4b026e-a0cc-49c1-959a-699485b08208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='자세히 보기'])[1]/preceding::span[1]</value>
      <webElementGuid>4261aa3e-5460-48ac-b032-6d1256ab333a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='게임 소개'])[2]/preceding::span[1]</value>
      <webElementGuid>6c0dbd87-e614-4746-a8ad-9aab71d3e5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>db7f61cb-f7c9-4e0c-9fb0-a2de02ba8ced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
