<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__css-uwwqev_1</name>
   <tag></tag>
   <elementGuidId>08d4a274-45e1-406f-9124-752816cdc575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-youtube > svg.css-uwwqev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6a7a582f-2c41-46b7-8f8f-fba17b8c1c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 60 60</value>
      <webElementGuid>9e6536f7-b935-4727-8a84-696e193c999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b5f645fd-61fa-41ed-8ac7-7bf860f3ffdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a49af88b-db6f-4123-bcb5-17648723abdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-uwwqev</value>
      <webElementGuid>d0186223-bbe5-4876-9b24-6c9dbda326c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-youtube&quot;)/svg[@class=&quot;css-uwwqev&quot;]</value>
      <webElementGuid>2b539460-d54a-405c-8bad-6fb9fbee8102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>1dc7cc91-ccff-4df1-90c8-8d2ca8b39e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커뮤니티'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>e9577846-9489-4ce7-aea5-5b1266492981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>de74d480-c708-4f64-9205-f57c38cfc0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='자세히 보기'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>47f397ae-77fa-479c-b0b7-c14dc0acf046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
