<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__css-uwwqev_1_2</name>
   <tag></tag>
   <elementGuidId>8d463f06-5ac3-4b2d-a9fc-23e44b786179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#global-navigation-facebook > svg.css-uwwqev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f9a2db07-ffe6-4a61-ac36-1996e3995c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 101 101</value>
      <webElementGuid>f97c6cd8-6a97-49ba-bf38-a27be8f13bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ce3b6fb1-c4e9-436c-a0c7-300debd590fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>952c7d6e-2a65-49e2-b15f-e58c8ecde6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-uwwqev</value>
      <webElementGuid>36c2d0b0-efe9-48f3-9b4c-c840003c71cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-navigation-facebook&quot;)/svg[@class=&quot;css-uwwqev&quot;]</value>
      <webElementGuid>075247e3-7dc7-4f0e-a22b-d9fc6beffaf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가이드북'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>b2966ffe-bb2e-4707-94b6-802e6f62739b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커뮤니티'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>48bd6354-3fb3-469a-87be-9d2655f6b74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구독하기'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>59b3c023-ce9f-452d-9ed1-db8cf9ca4f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='자세히 보기'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>5e3161ae-e152-4453-99aa-daf6ed5aae3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
