<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>a1f8b55a-c3df-470c-b1bd-484157e28211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.rnb-btn-col-content > tbody > tr > td > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>231cd31f-d107-4d9e-a39f-b03798bed9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>9f988925-9b6a-4b96-b232-3ebdf301e5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>21453526-bdd0-4fea-8696-5ef94057dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>21c53694-9f11-428d-9bd0-1427ef604d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>662dada3-c0ec-4d71-92e6-60e7bdcd7652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>76aff9da-2ab3-4304-9f2f-7c4bcf3fab5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>725c3bc3-6163-4d5a-9f2b-246dc7fe1e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>a59e8219-21fe-4827-99fd-bfe58a7a4a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8638231b-7f26-4a52-9dec-301e5a0d52a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>0d0a831f-49c7-45c0-bf36-ea4b42dcca3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>16bd6d61-c81c-4147-841a-37b3a068ecf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>fe6dbe08-fdb5-4b6c-b375-8839eb27e80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3cdcccc-5ecb-42a4-8c5a-56e3261b25c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>09fc484c-cb90-4205-8a30-3339ef837b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>9a04026e-01f4-4fc6-9268-1c3fc4d33f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>93b794f5-d094-4090-94c6-7f9b12dba759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>7773a5d2-3c01-4126-962b-18d991f58694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>c0c32008-f265-4f41-81de-be5f687cb524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 챕터 1'])[2]/following::a[12]</value>
      <webElementGuid>ff88a0e6-f574-4009-b576-b32f4c2dab82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in browser'])[1]/following::a[15]</value>
      <webElementGuid>11b8582c-4979-48e7-a795-47822d0d160c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul, Rep. of Korea'])[1]/preceding::a[5]</value>
      <webElementGuid>c9955c4a-655b-4924-9784-861d9da51b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='브릭시티 코덱스 목록으로 가기']/parent::*</value>
      <webElementGuid>cec73fb5-2e2c-4f78-ae66-775b1b2bd1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA')]</value>
      <webElementGuid>f4d0f4e4-1ad2-438a-b671-86ff97ec5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>98da1798-d5e2-4c2e-bc1b-2ae0c3d26349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA' and (text() = '브릭시티 코덱스 목록으로 가기' or . = '브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>56e86eb3-cc72-446e-b698-92db6058769f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
