<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Brixity</name>
   <tag></tag>
   <elementGuidId>d23952c1-7604-4211-8b7c-c789b9c802f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.gmql0nx0.l94mrbxd.p1ri9a11.lzcic4wl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_xw']/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/span/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>eaddbcff-09d3-488e-97dc-c94520e4615c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gmql0nx0 l94mrbxd p1ri9a11 lzcic4wl</value>
      <webElementGuid>d8db5dc6-1e28-4beb-84ca-8023fbeaeb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brixity</value>
      <webElementGuid>b17abb45-4f20-4a36-af07-04a85c614ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_xw&quot;)/div[1]/div[1]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb&quot;]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb&quot;]/div[@class=&quot;du4w35lb l9j0dhe7 cbu4d94t j83agx80&quot;]/div[@class=&quot;j83agx80 cbu4d94t l9j0dhe7 jgljxmt5 be9z9djy&quot;]/div[@class=&quot;j83agx80 cbu4d94t d6urw2fd dp1hu0rb l9j0dhe7 du4w35lb&quot;]/div[@class=&quot;l9j0dhe7 dp1hu0rb cbu4d94t j83agx80&quot;]/div[1]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb j83agx80 pfnyh3mw taijpn5t gs1a9yip owycx6da btwxx1t3 ihqw7lf3 cddn0xzi&quot;]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb j83agx80 cbu4d94t hpfvmrgz rj1gh0hx buofh1pr g5gj957u hv4rvrfc dati1w0a marjyy4e&quot;]/div[@class=&quot;k4urcfbm&quot;]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb j83agx80 pfnyh3mw i1fnvgqd aovydwv3 lhclo0ds btwxx1t3 discj3wi dlv3wnog rl04r1d5 enqfppq2 muag1w35&quot;]/div[@class=&quot;rq0escxv l9j0dhe7 du4w35lb j83agx80 cbu4d94t d2edcug0 hpfvmrgz buofh1pr g5gj957u o8rfisnq ph5uu5jm b3onmgus ecm0bbzt on77hlbc ihqw7lf3&quot;]/div[@class=&quot;tr9rh885&quot;]/div[@class=&quot;j83agx80 cbu4d94t obtkqiv7 sv5sfqaa&quot;]/div[@class=&quot;bi6gxh9e aov4n071&quot;]/span[@class=&quot;d2edcug0 hpfvmrgz qv66sw1b c1et5uql oi732d6d ik7dh3pa ht8s03o8 a8c37x1j fe6kdd0r mau55g9w c8b282yb keod5gw0 nxhoafnm aigsh9s9 ns63r2gh rwim8176 m6dqt4wy h7mekvxk hnhda86s oo9gr5id hzawbc8m&quot;]/h1[@class=&quot;gmql0nx0 l94mrbxd p1ri9a11 lzcic4wl&quot;]</value>
      <webElementGuid>0438dbbd-a91c-40aa-828f-4d73a90547c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_xw']/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/span/h1</value>
      <webElementGuid>7a8e2c28-ead4-4cdd-a543-487e61af47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='계정을 잊으셨나요?'])[1]/following::h1[1]</value>
      <webElementGuid>260505c1-a06b-412a-adc5-0e3209f62239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그인'])[2]/following::h1[1]</value>
      <webElementGuid>8732d47e-8334-4780-84ca-dff936f2424b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@brixity'])[1]/preceding::h1[1]</value>
      <webElementGuid>19f7552f-2710-4db0-aba9-1718987f773f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brixity']/parent::*</value>
      <webElementGuid>d923438b-092f-4d37-849f-9fe95c73e0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>75fc33e9-d6a2-4eb4-acbc-f5678aaa0edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Brixity' or . = 'Brixity')]</value>
      <webElementGuid>af8441a2-c03d-4af8-a0ff-d0db52f7e599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
