<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>d1ba9341-20dc-48ff-afbb-a252c3a75d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.rnb-btn-col-content > tbody > tr > td > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71847b64-90b6-4164-af91-e1b6f51f17e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>4c9314fb-ff79-4477-a2ae-51d13909f05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>5b8f05ca-a8d6-4028-ad39-a80180dfa825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>29458c97-426b-4f0a-9ba5-915bfac3542a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22b4b411-f95a-43a0-abf0-82bf62745ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>1acd71db-6228-496e-b5fe-02779485780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>d5b49342-80bb-4009-b882-fffe037eb2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>79e327d3-975b-4de3-a15f-3149f4331ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>2250364c-51c6-4ace-afe0-f53b2a544a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>95f13702-444f-420f-9580-d5a9c8402f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 챕터 2'])[2]/following::a[12]</value>
      <webElementGuid>496bd8fc-e278-413b-972e-02101fd71159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in browser'])[1]/following::a[15]</value>
      <webElementGuid>968b6c8f-c673-4af4-a2e6-380d459ddf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul, Rep. of Korea'])[1]/preceding::a[5]</value>
      <webElementGuid>8762176b-d724-48b8-8cbf-54bd226089e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='브릭시티 코덱스 목록으로 가기']/parent::*</value>
      <webElementGuid>20af3aeb-ac3a-4cde-8f54-b27cc09005d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA')]</value>
      <webElementGuid>f7241c8a-2bea-4117-ab36-bb9fdb5fa120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>cd62b261-c458-4ce8-aa97-2edba538c194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA' and (text() = '브릭시티 코덱스 목록으로 가기' or . = '브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>2d937f51-eb6d-4e0e-812d-186ab028cef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
