<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>5275cd9b-d90d-43d1-a870-d8bf87cacd06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.rnb-btn-col-content > tbody > tr > td > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>475b3a77-743a-4291-bee7-57fac20a0fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a47393b0-7353-4a49-a7b2-f80e9702e334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://drive.google.com/file/d/179RNjIO8kq-9gA2AklAM_nXhOMCbVgJk/view?usp=sharing</value>
      <webElementGuid>49628713-5a56-4d9a-8edd-a54c88267fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 가이드북 목록으로 가기</value>
      <webElementGuid>eba60044-5f0b-4f87-a439-8e432af7c42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;main-template&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;templateContainer&quot;]/tbody[1]/tr[12]/td[1]/div[1]/table[@id=&quot;Layout_51&quot;]/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>be31a327-87c6-43e9-bbd5-3acf5a80716d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>18a567e3-f978-4e54-90c6-0596bb164947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'브릭시티 가이드북 목록으로 가기')]</value>
      <webElementGuid>aea07547-650c-4e1d-b8f2-cadd1be8c6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 챕터 5'])[2]/following::a[10]</value>
      <webElementGuid>178dde04-057f-4f6e-93a9-52c12e3cd7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in browser'])[1]/following::a[13]</value>
      <webElementGuid>0690084a-198d-44fd-959b-c476128305de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul, Rep. of Korea'])[1]/preceding::a[5]</value>
      <webElementGuid>726877de-3800-435d-bcfd-b2ca8ceb99c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='브릭시티 가이드북 목록으로 가기']/parent::*</value>
      <webElementGuid>30d061bd-0895-4f12-8d4a-ceb723d50e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://drive.google.com/file/d/179RNjIO8kq-9gA2AklAM_nXhOMCbVgJk/view?usp=sharing')]</value>
      <webElementGuid>c4eb4889-4d48-4cdc-abd9-375d1209417f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>b9125de6-7c5f-4c44-b3bb-2f82cf197be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://drive.google.com/file/d/179RNjIO8kq-9gA2AklAM_nXhOMCbVgJk/view?usp=sharing' and (text() = '브릭시티 가이드북 목록으로 가기' or . = '브릭시티 가이드북 목록으로 가기')]</value>
      <webElementGuid>b1efc968-ee89-4c60-90e4-f9576b903450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
