<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>a3b7b970-1ddb-4bf1-8641-45e41790d084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.rnb-btn-col-content > tbody > tr > td > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3274a35-723d-4d3f-aaac-f2cf88e56b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>740e5806-49dd-4438-8032-3e5d4a95c265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>77b2a08a-f93b-4d70-80ee-c6e323259b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>b2d92ece-af6a-4628-8449-69c304c2ae86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73034282-9c73-4bab-94ff-167927507a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA</value>
      <webElementGuid>ce677e01-d2f7-4d9f-a1e3-311afff0b28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>브릭시티 코덱스 목록으로 가기</value>
      <webElementGuid>487c05b0-551a-4d30-b19d-72fa3042cf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout_51&quot;)/tbody[1]/tr[1]/td[@class=&quot;rnb-del-min-width&quot;]/table[@class=&quot;mso-button-block rnb-container&quot;]/tbody[1]/tr[2]/td[@class=&quot;rnb-container-padding&quot;]/table[@class=&quot;rnb-columns-container&quot;]/tbody[1]/tr[1]/th[@class=&quot;rnb-force-col&quot;]/table[@class=&quot;rnb-col-1&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rnb-btn-col-content&quot;]/tbody[1]/tr[1]/td[1]/span[1]/a[1]</value>
      <webElementGuid>2701dc44-b798-42ab-9670-eec8bf5bca99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Layout_51']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>33de5870-9172-4d54-98e8-1134fe938fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>78d7ba85-847c-456f-9ee0-5988b1b64d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브릭시티 세계관 가이드북 챕터 3'])[1]/following::a[9]</value>
      <webElementGuid>c8c39416-07ee-4dd8-a607-9e35bfff770f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in browser'])[1]/following::a[12]</value>
      <webElementGuid>d32d04c2-a927-4d1b-bdb8-34b729ad5756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seoul, Rep. of Korea'])[1]/preceding::a[5]</value>
      <webElementGuid>5a465211-2135-44fd-9b9e-02e1e9f5edc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='브릭시티 코덱스 목록으로 가기']/parent::*</value>
      <webElementGuid>e870bcc7-a726-49e8-926d-dbbfd86bd935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA')]</value>
      <webElementGuid>ddaf29d4-656e-4ae3-b8b6-87718feb39d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td/table/tbody/tr/td/span/a</value>
      <webElementGuid>c2a35fb3-41bb-4500-82a0-0e2583e9b9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://62qww.r.bh.d.sendibt3.com/mk/mr/g83lGxMn6KTq8qNeKavqU9LNRTL0hjEW2ZvEUxa7M7jrnvUwaeGhQm2r0q3jCynprOKQv1Cm1bcxzJrgM26RaEAWOeoBilGfX1xO_SHpQadXcUG0JA' and (text() = '브릭시티 코덱스 목록으로 가기' or . = '브릭시티 코덱스 목록으로 가기')]</value>
      <webElementGuid>b06a6b8c-6939-4dad-ba61-614c53b6b47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
